repos:

# General checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
    -   id: trailing-whitespace             # Check for trailing whitespace
    -   id: end-of-file-fixer               # Check for new line ending
    -   id: check-added-large-files         # Check for large files
    -   id: check-yaml                      # Check for valid yaml
    -   id: check-json                      # Check for valid json
    -   id: check-xml                       # Check for valid xml
        stages: [commit]

# Format code
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.11
      args: [--line-length=79]
      stages: [commit]

# Check PEP8 style
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # E203: Whitespace before ':'
        # F401: Module imported but never used
        # F841: Unused variable
        # W503: Line break before binary operator
        args: [
            --max-line-length=79,
            '--ignore=E203,F401,F841,W503'
            ]
        stages: [commit]

# Check doc strings
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        stages: [commit]

# Check for unused import statements
-   repo: https://github.com/hadialqattan/pycln
    rev: 'v2.1.5'
    hooks:
    -   id: pycln
        stages: [commit]

# Run unittests through coverage
- repo: local
  hooks:
    -   id: unittest
        name: unittest
        entry: coverage run -m unittest discover -s tests
        language: python
        types: [python]
        pass_filenames: false
        always_run: false
        stages: [commit]

# CHeck test coverage
- repo: local
  hooks:
  -   id: test-coverage
      name: test-coverage
      entry:  coverage report --omit=./tests/test_*.py --fail-under=100
      language: python
      types: [python]
      pass_filenames: false
      always_run: false
      stages: [commit]
